package org.example.Model.distributions;

/**
 * Random number generator based on the geometric distribution.
 * Automatically generated by the {@code MetaGenerator}.
 *
 * @version 1.0, Thu Oct 03 10:27:38 BST 2002
 * @author F. Mallet from C. Simatos's original
 */
public class Geometric extends Generator implements DiscreteGenerator {

    /**
     * Probability of success in a trial.
     */
    private double prob;

    /**
     * Creates a geometric random number generator.
     * The seed is automatically provided by the {@code SeedGenerator}.
     *
     * @param prob probability of success in a trial
     */
    public Geometric(double prob) {
        super();
        set(prob);
    }

    /**
     * Creates a geometric random number generator with a specific seed.
     *
     * @param prob probability of success in a trial
     * @param seed initial seed for the generator; two instances with
     *             the same seed will generate the same sequence of numbers
     */
    public Geometric(double prob, long seed) {
        super(seed);
        set(prob);
    }

    /**
     * Sets the probability parameter of the geometric distribution.
     *
     * @param prob probability of success
     * @throws ParameterException if the probability is not between 0 and 1
     */
    private void set(double prob) {
        if (prob <= 0 || prob >= 1)
            throw new ParameterException("Geometric: The probability of success must be between 0 and 1.");
        this.prob = prob;
    }

    /**
     * Generates a new random number from the geometric distribution.
     *
     * @return the next random number in the sequence
     */
    public long sample() {
        return distrib.geometric(prob);
    }
}