package org.example.Model.distributions;

/**
 * Random number generator based on the inverse gamma distribution.
 * Automatically generated by {@code MetaGenerator}.
 *
 * @version 1.0, Thu Oct 03 10:44:05 BST 2002
 * @author F. Mallet from C. Simatos's original
 */
public class Invgamma extends Generator implements ContinuousGenerator {

    /**
     * Scale parameter of the inverse gamma distribution.
     */
    private double scale;

    /**
     * Shape parameter of the inverse gamma distribution.
     */
    private double shape;

    /**
     * Creates an inverse gamma random number generator.
     * The seed is automatically provided by the {@code SeedGenerator}.
     *
     * @param scale the scale parameter of the distribution
     * @param shape the shape parameter of the distribution
     */
    public Invgamma(double scale, double shape) {
        super();
        set(scale, shape);
    }

    /**
     * Creates an inverse gamma random number generator with a specific seed.
     *
     * @param scale the scale parameter of the distribution
     * @param shape the shape parameter of the distribution
     * @param seed the initial seed for the generator; two instances with
     *             the same seed will generate the same sequence of numbers
     */
    public Invgamma(double scale, double shape, long seed) {
        super(seed);
        set(scale, shape);
    }

    /**
     * Sets the parameters of the inverse gamma distribution.
     *
     * @param scale the scale parameter
     * @param shape the shape parameter
     * @throws ParameterException if scale or shape are not greater than zero
     */
    private void set(double scale, double shape) {
        if (scale <= 0.0 || shape <= 0.0)
            throw new ParameterException("Invgamma: The scale and shape parameters must be greater than 0.");
        this.scale = scale;
        this.shape = shape;
    }

    /**
     * Generates a new random number from the inverse gamma distribution.
     *
     * @return the next random number in the sequence
     */
    public double sample() {
        return distrib.invgamma(scale, shape);
    }
}