package org.example.Model.distributions;

/**
 * Random number generator based on the logistic distribution.
 * Automatically generated by {@code MetaGenerator}.
 *
 * @version 1.0, Thu Oct 03 10:51:22 BST 2002
 * @author F. Mallet from C. Simatos's original
 */
public class Logistic extends Generator implements ContinuousGenerator {

    /**
     * Location parameter of the logistic distribution.
     */
    private double location;

    /**
     * Scale parameter of the logistic distribution.
     */
    private double scale;

    /**
     * Creates a logistic random number generator.
     * The seed is automatically provided by the {@code SeedGenerator}.
     *
     * @param location the location parameter of the distribution
     * @param scale the scale parameter of the distribution
     */
    public Logistic(double location, double scale) {
        super();
        set(location, scale);
    }

    /**
     * Creates a logistic random number generator with a specific seed.
     *
     * @param location the location parameter of the distribution
     * @param scale the scale parameter of the distribution
     * @param seed the initial seed for the generator; two instances with
     *             the same seed will generate the same sequence of numbers
     */
    public Logistic(double location, double scale, long seed) {
        super(seed);
        set(location, scale);
    }

    /**
     * Sets the parameters of the logistic distribution.
     *
     * @param location the location parameter
     * @param scale the scale parameter
     * @throws ParameterException if the scale parameter is not greater than zero
     */
    private void set(double location, double scale) {
        if (scale <= 0)
            throw new ParameterException("Logistic: The scale parameter must be greater than 0.");
        this.location = location;
        this.scale = scale;
    }

    /**
     * Generates a new random number from the logistic distribution.
     *
     * @return the next random number in the sequence
     */
    public double sample() {
        return distrib.logistic(location, scale);
    }
}