package org.example.Model.distributions;

/** A random number generator based on the negexp distribution.
  * automatically generated by <code>MetaGenerator</code> 
  * @version 1.0, Thu Oct 03 10:57:43 BST 2002
  * @author F.Mallet from C.Simatos's original
  */

public class Negexp extends Generator implements ContinuousGenerator {
    /**
     * Mean of the negative exponential distribution.
     */
    private double mean;
    /**
     * The seed is automatically provided by the <code>SeedGenerator</code>.
     *
     * @param mean The mean value of the negative exponential distribution
     */
    public Negexp(double mean) {
        super();
        set(mean);
    }

    /**
     * The constructor with which a specific seed is set for the random
     * number generator.
     *
     * @param mean The mean value of the negative exponential distribution
     * @param seed The initial seed for the generator; two instances with
     *             the same seed will generate the same sequence of numbers
     */
    public Negexp(double mean, long seed) {
        super(seed);
        set(mean);
    }

    /**
     * Sets the mean parameter of the distribution.
     *
     * @param mean the mean of the distribution
     * @throws ParameterException if the mean is not greater than zero
     */
    private void set(double mean) {
        if (mean<=0)
            throw new ParameterException("Negexp: The mean must be greater than 0.");
        this.mean = mean;
    }

    /**
     * Updates the mean parameter of the distribution.
     *
     * @param mean the new mean value
     * @throws ParameterException if the mean is not greater than zero
     */
    public void setMean(double mean) {
        if (mean<=0)
            throw new ParameterException("Negexp: The mean must be greater than 0.");
        this.mean = mean;
    }



    /**
     * Generate a new random number.
     * @return The next random number in the sequence
     */
    public double sample() { 
         return distrib.negexp(mean);
    }
}
