package org.example.Model.distributions;

/** A random number generator based on the tstudent distribution.
  * automatically generated by <code>MetaGenerator</code>
  * @version 1.0, Thu Oct 03 11:03:30 BST 2002
  * @author F.Mallet from C.Simatos's original
  */

public class Tstudent extends Generator implements ContinuousGenerator {
    /**
     * Degrees of freedom of the t-distribution.
     */
    private long deg_freedom;
    /**
     * The seed is automatically provided by the <code>SeedGenerator</code>.
     *
     * @param deg_freedom The degrees of freedom for the distribution
     */
    public Tstudent(long deg_freedom) {
        super();
        set(deg_freedom);
    }

    /**
     * Creates a Student's t random number generator with a specific seed.
     *
     * @param deg_freedom degrees of freedom of the distribution
     * @param seed the initial seed for the generator; two instances with
     *             the same seed will generate the same sequence of numbers
     */
    public Tstudent(long deg_freedom, long seed) {
        super(seed);
        set(deg_freedom);
    }

    /**
     * Sets the degrees of freedom parameter.
     *
     * @param deg_freedom degrees of freedom
     * @throws ParameterException if the value is not positive
     */
    private void set(long deg_freedom) {
        if (deg_freedom<=0)
            throw new ParameterException("Tstudent: The degrees of freedom must be a positive integer.");
        this.deg_freedom = deg_freedom;
    }

    /**
     * Generate a new random number.
     * @return The next random number in the sequence
     */
    public double sample() {
         return distrib.tstudent(deg_freedom);
    }
}
