package org.example.Model.distributions;

/** A random number generator based on the uniform distribution.
  * automatically generated by <code>MetaGenerator</code> 
  * @version 1.0, Thu Oct 03 11:04:34 BST 2002
  * @author F.Mallet from C.Simatos's original
  */

public class Uniform extends Generator implements ContinuousGenerator {
    /**
     * Lower bound of the distribution.
     */
    private double min;

    /**
     * Upper bound of the distribution.
     */
    private double max;
    /**
     * Creates a uniform random number generator.
     * The seed is automatically provided by the {@code SeedGenerator}.
     *
     * @param min lower bound of the distribution
     * @param max upper bound of the distribution
     */
    public Uniform(double min, double max) {
        super();
        set(min, max);
    }

    /**
     * Creates a uniform random number generator with a specific seed.
     *
     * @param min lower bound of the distribution
     * @param max upper bound of the distribution
     * @param seed the initial seed for the generator; two instances with
     *             the same seed will generate the same sequence of numbers
     */
    public Uniform(double min, double max, long seed) {
        super(seed);
        set(min, max);
    }

    /**
     * Sets the parameters of the uniform distribution.
     *
     * @param min lower bound
     * @param max upper bound
     * @throws ParameterException if max is not greater than min
     */
    private void set(double min, double max) {
        if (max<=min)
            throw new ParameterException("Uniform: The maximum must be greater than the minimum.");
        this.min = min;
        this.max = max;
    }

    /**
     * Generate a new random number.
     * @return The next random number in the sequence
     */
    public double sample() { 
         return distrib.uniform(min, max);
    }
}
