package org.example.Model.distributions;

/** A random number generator based on the weibull distribution.
  * automatically generated by <code>MetaGenerator</code> 
  * @version 1.0, Thu Oct 03 11:05:46 BST 2002
  * @author F.Mallet. Adaptation of C.Simatos's original
  */

public class Weibull extends Generator implements ContinuousGenerator {
    /**
     * Scale parameter of the Weibull distribution.
     */
    private double scale;

    /**
     * Shape parameter of the Weibull distribution.
     */
    private double shape;
    /**
     * Creates a Weibull random number generator.
     * The seed is automatically provided by the {@code SeedGenerator}.
     *
     * @param scale the scale parameter of the distribution
     * @param shape the shape parameter of the distribution
     */
    public Weibull(double scale, double shape) {
        super();
        set(scale, shape);
    }

    /**
     * Creates a Weibull random number generator with a specific seed.
     *
     * @param scale the scale parameter of the distribution
     * @param shape the shape parameter of the distribution
     * @param seed the initial seed for the generator; two instances with
     *             the same seed will generate the same sequence of numbers
     */
    public Weibull(double scale, double shape, long seed) {
        super(seed);
        set(scale, shape);
    }

    /**
     * Sets the parameters of the Weibull distribution.
     *
     * @param scale the scale parameter
     * @param shape the shape parameter
     * @throws ParameterException if scale or shape are not greater than zero
     */
    private void set(double scale, double shape) {
        if (scale<=0 || shape <= 0)
            throw new ParameterException("Weibull:  Scale and shape parameters must be greater than 0.");
        this.scale = scale;
        this.shape = shape;
    }

    /**
     * Generate a new random number.
     * @return The next random number in the sequence
     */
    public double sample() { 
         return distrib.weibull(scale, shape);
    }
}
